### ISSUE TITLE
Repository Permissions

### ISSUE THREAD

**Issue by danielbarion** [L2jBrasil/L2jBrasilWeb#5]
@LeonanCarvalho fera, preciso de permissão nesse repositório, um membro da JBr está dando continuidade e estudando (estou acompanhando ele) mas não consegue fazer o push da nova branch; eu não tenho acesso as settings desse repositório para adiciona-lo como contribuidor.

**Comment by danielbarion** [comment]
Caso não seja possível setar as permissões pra mim nesse repositório, adiciona o rapaz como colaborador por favor. 

Obrigado

**Comment by nascimentolh** [comment]
Bom Dia,

Sou eu, fico no aguardo!

**Comment by LeonanCarvalho** [comment]
Eu não sei se tem como eu lhe dar permissão para adicionar pessoas ao projeto, mas irei investigar, já de antemão vou adicioná-lo.

**Comment by danielbarion** [comment]
Beleza, obrigado.

**Comment by LeonanCarvalho** [comment]
Eu te adicionei como adm do projeto, da um confere se você consegue gerenciar os usuários. 
Caso sim, pode fechar o issue :)
